AOC = arm-none-eabi-objcopy
KERNEL_BIN = kernel.bin
KERNEL_ELF = target/$(TARGET)/debug
MAIN_FILE = src/main.rs

AFLAGS = -O binary
TARGET = thumbv7m-none-eabi
FFLAGS = -v -g 0x8000000
USB_PORT = /dev/ttyUSB0

